image: maven:latest
variables:
  SONAR_TOKEN: $JOB_SONAR_TOKEN
  SONAR_HOST_URL: "https://sonarcloud.io"
  GIT_DEPTH: 0

sonarcloud-backend-job-service:
  stage: sonar-job
  script:
    - cd "${CI_PROJECT_DIR}/backend/job-service"
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=job-service -Dsonar.coverage.exclusions=**/entity/*,**/JobServiceApplication.java,**/exception/*,**/dto/*
  allow_failure: true
  only:
    - merge_requests
    - main
