server:
  port: 9006

spring:
  application:
    name: SAVEJOB-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.142.147.227:8761/eureka/
  instance:
    hostname: 3.142.147.227
