image: maven:latest
variables:
  SONAR_TOKEN: $SAVE_JOB_SONAR_TOKEN
  SONAR_HOST_URL: "https://sonarcloud.io"
  GIT_DEPTH: 0

sonarcloud-backend-saveJob-service:
  stage: sonar-saveJob
  script:
    - cd "${CI_PROJECT_DIR}/backend/saveJob-service"
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=save-job -Dsonar.coverage.exclusions=**/entity/*,**/SaveJobServiceApplication.java
  allow_failure: true
  only:
    - merge_requests
    - main
